### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yoonthegoon** [yoonthegoon/connect_four.rs#2]
- [ ] implement negamax
- [ ] add test protocol
- [ ] add alpha-beta pruning to negamax
- [ ] add transposition table
  - [ ] write hasher
- [ ] add to this list
